seed: 10
out_dir: data/2025-02-24/interventional
type: interventional

model:
  type: gaussian_relu
  n_vars: 5
  name_n_chars: 6

data:
  n_models: 100
  n_questions_per_model: 10
  n_observe: 2
  n_intervene: 1
  actions: [-10, 10]
  split:
    train: 8
    dev: 1
    test: 1
  prompt:
    system: >
      You will be given a model name and the relevant variable names. 
      You will be given an observation of a subset of these variables. 
      Then you will be asked to answer some questions about the other variables, given some interventions.
      Please answer to the best of your ability.
    user: >
      The model name is {model_name}.
      The relevant variables are {var_names}.
      You observe that {observation}.
      The intervention is: {intervention}.

      Question: {question}
