seed: 10
out_dir: data/2025-06-03-1/interventional_distribution
type: interventional

model:
  type: discrete_cpt
  n_vars:
    train: [5]
    eval: [5]
  n_vals:
    train: [2, 3]
    eval: [2, 3]

data:
  format: parquet
  n_models: 
    train: 50
    dev: 25
    test: 25
  n_questions_per_model:
    train: 100
    dev: 50
    test: 50
  n_observe: 0
  n_intervene: 1
  prompt:
    system: |-
        You're a graduate student well-trained in causal inference techniques. You understand the difference between observational, interventional, and counterfactual queries. You know the different techniques for identifying the queries (or concluding it's non-identifiable). You are in a qualifying exam, and you are asked to compute probability queries over a structural causal model defined over discrete variables. 
  
        Format your solution as follows:
          Only state your final answer to the query. Write it out in a single line, as a list of numbers such as [0.1, 0.7, 0.2] or [0.1, 0.9] depending on how many values the variable can take on. Don't include any additional explanations in this section. Round you answer to the nearest two digits.

    user: |-
      Here's a structural causal model over discrete random variables. The Variables are {var_names}. Here are the Values they can take on.

      {values}

      Here's the causal directed acyclic graph (DAG):

      {graph}

      Here are the conditional probability tables (CPT) associated with the DAG:

      {cpts}

      Here's your {question}
      
      ----------

      Now start your solution process. Be precise.
  
    reference:
      type: distribution
  max_tries_for_uniqueness: 100
